- name: Start Azure VM
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  tasks:
    - name: Start virtual machine
      azure_rm_virtualmachine:
        resource_group: RG-ManageIQ
        name: VM-01
        started: yes
